name: bangla_fonts
description: A flutter package to load and use popular Bangla fonts dynamically from CDN without increasing app size.
version: 1.0.2

homepage: https://github.com/oxfaysal/bangla_fonts
repository: https://github.com/oxfaysal/bangla_fonts
issue_tracker: https://github.com/oxfaysal/bangla_fonts/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0